<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="../public/css/bootstrap.css">    
        <link rel="stylesheet" type="text/css" href="../public/css/styles.css">
    </head>
 
    <body>
        <div class="container">
                <div class="row">
                    <h3>Student Grade Report App</h3>
                </div>
                <div class="row formContainer readMe">
                    <p>
                        <a href="Create" class="btn btn-success">Create</a>
                    </p>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Student Id</th>
                                <th>Student Name</th>
                                <th>Student Percent</th>
                                <th>Student Letter Grade</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            
                            foreach ($data as $student) {
                                    echo '<tr>';
                                    echo '<td>'. $student['studentid'] . '</td>';
                                    echo '<td>'. $student['studentname'] . '</td>';
                                    echo '<td>'. $student['studentpercent'] . '</td>';
                                    echo '<td>'. $student['studentlettergrade'] . '</td>';
                                    echo '<td width=250>';
                                    echo '<a class="btn" href="Read?studentid='.$student['studentid'].'">Read</a>';
                                    echo ' ';
                                    echo '<a class="btn btn-success" href="Update?studentid='.$student['studentid'].'">Update</a>';
                                    echo ' ';
                                    echo '<a class="btn btn-danger" href="Delete?studentid='.$student['studentid'].'&studentName='.$student['studentname'].'">Delete</a>';
                                    echo '</td>';
                                    echo '</tr>';
                            }
                            ?>
                        </tbody>
                </table>
            </div>
        </div> <!-- /container -->
    <script src="../public/js/bootstrap.min.js"></script>
    </body>
</html>